// --------------------------------------------------------------------------------------------------------------------
// <copyright file="AWSDummyFactory.cs" company="Naos Project">
//    Copyright (c) Naos Project 2019. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in Naos.AWS.Test source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace Naos.AWS.Domain.Test
{
    using System.Linq;
    using FakeItEasy;
    using Naos.Database.Domain;
    using OBeautifulCode.AutoFakeItEasy;
    using OBeautifulCode.Serialization;

    /// <summary>
    /// A Dummy Factory for types in <see cref="AWS"/>.
    /// </summary>
#if !NaosAWSRecipesProject
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("Naos.AWS.Test", "See package version number")]
    internal
#else
    public
#endif
    class AWSDummyFactory : DefaultAWSDummyFactory
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AWSDummyFactory"/> class.
        /// </summary>
        public AWSDummyFactory()
        {
            AutoFixtureBackedDummyFactory.UseRandomInterfaceImplementationForDummy<IResourceLocator>();

            AutoFixtureBackedDummyFactory.AddDummyCreator(() =>
            {
                var result = new S3StreamConfig(
                    A.Dummy<string>(),
                    A.Dummy<StreamAccessKinds>().ThatIsNot(StreamAccessKinds.None),
                    A.Dummy<SerializerRepresentation>(),
                    A.Dummy<SerializationFormat>(),
                    Some.ReadOnlyDummies<S3ResourceLocator>().ToList());

                return result;
            });
        }
    }
}
